### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by keeth** [tonyvanriet/clj-slack-client#2]
A minor detail... currently every message is println'd to the console, and other logging done by this library is done this way too ('reconnecting...').  would be nice to either silence these, and/or use clojure.logging or something.

**Comment by tonyvanriet** [comment]
@Janiczek 's 7405f8553c31960b31d3b31fa240fee40cf15669 adds an option map to the connect call that can be used to silence the println logging. I'll look into integrating a more appropriate logging library. Thanks @keeth.
