### ISSUE TITLE
Reconnect issue

### ISSUE THREAD

**Issue by Janiczek** [tonyvanriet/clj-slack-client#4]
Every now and then my long-running Slack bot "dies". It still runs all the schedulers etc but is not connected to Slack. Here is what the log prints out. Maybe it's connected to #1 ?

(Before that nothing interesting happens, for hours and hours.)

I am using `[clj-slack-client "0.1.4-SNAPSHOT"]`.

```
reconnecting...
Zář 07, 2015 4:54:17 DOP. manifold.stream invoke
SEVERE: error in stream handler
java.util.concurrent.TimeoutException: timed out after 60000.0 milliseconds
        at manifold.deferred$timeout_BANG_$fn__6904.invoke(deferred.clj:1082)
        at manifold.time$fn__6390$in__6393$f__6394.invoke(time.clj:144)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at manifold.utils$thread_factory$reify__6304$fn__6306.invoke(utils.clj:25)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)

{:type team_migration_started}
Zář 07, 2015 4:54:17 DOP. aleph.http.client invoke
WARNING: error in websocket client
java.io.IOException: readAddress() failed: Koncový komunikační bod není připojen # (in English: transport endpoint is not connected)
        at io.netty.channel.epoll.Native.newIOException(Native.java:124)
        at io.netty.channel.epoll.Native.ioResult(Native.java:140)
        at io.netty.channel.epoll.Native.readAddress(Native.java:242)
        at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:232)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:610)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollRdHupReady(AbstractEpollStreamChannel.java:573)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:315)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:250)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by tonyvanriet** [comment]
It looks like this happened as a result of Slack doing a server migration for your team. I thought the client would handle this scenario. 

@Janiczek, do you know if the team_migration_started event has happened every time you've seen this failure?

**Comment by Janiczek** [comment]
The same error has happened about a week ago, and I think I saw the
migration mentioned there too, so yes.

**Comment by keeth** [comment]
I'm seeing the same thing - disconnect after running for days.  I don't see any team_migration_started event in the logs.  Interestingly, I am running [node-slack-client](https://github.com/slackhq/node-slack-client) as well, and it disconnected around the same time.

They also have an open ticket, with similar symptoms: https://github.com/slackhq/node-slack-client/issues/53

**Comment by Janiczek** [comment]
@keeth They have recently resolved this. Can we look into it again in our Clojure client?

**Comment by tonyvanriet** [comment]
I might be able to find some time for it in the next week or so.

**Comment by Janiczek** [comment]
Ping ... :) Can I help you with this in any way? We use this library quite a bit in our company, so I have an interest for seeing this resolved :)

**Comment by tonyvanriet** [comment]
Hi @Janiczek , thanks for checking in. As you can tell I haven't made time to experiment with this. 

All I have thus far is this theory:
- there's some kind of network connectivity issue that lasts > 10s
- the `ping-loop` calls the `*reconnect*` fn which is specified in `core/connect`
- the reconnect fn calls `disconnect` then `connect`
- that `connect` call fails because the network connectivity issue is ongoing

I'm guessing the connect code needs to gracefully handle this exception and periodically retry.
Either that, or the connectivity logic needs to be re-written completely to emulate the changes made in the node reference client.

If you have any time to experiment with this, I'd love the help. Just let me know what you find, and I'll do the same if I do any work on it.

**Comment by Janiczek** [comment]
From [what I can read](https://github.com/slackhq/node-slack-client/blob/master/lib/clients/rtm/client.js#L329) in the node client, it handles reconnects this way:

``` clojure
(defn connect
   ;; ...
   (let [ ;; ...
         reconnect (fn [] (do (when (options :log)
                                (println "reconnecting..."))
                              (disconnect)
                              ;; TODO
                              ;; for 10 times try connecting
                              ;; with increasingly long timeouts
                              ;; (3 seconds * attempt number)
                              (connect api-token host-handle-event options)))]
        ;; ...
        ))
```

EDIT: Also, according to [this](https://api.slack.com/events/team_migration_started), maybe we're getting a `migration_in_process` error when reconnecting?

**Comment by tonyvanriet** [comment]
Some good progress on this...
I experimented with simply starting the ping earlier in the connection process. This way, if the connection isn't successfully established, the ping will eventually initiate a reconnect and that will repeat until the connection is finally successful.
I'm now able to disconnect and reconnect to the internet and the bot will automatically reconnect to Slack.

I expect to be able to do a Clojars release tomorrow night after some further testing.

**Comment by tonyvanriet** [comment]
I can't be certain this will solve your exact problem, @Janiczek , but I'm optimistic.
It's kind of sad that I waited 7 months to move one line of code.

Anyway, can you try out `[clj-slack-client "0.1.6-SNAPSHOT"]` and let me know if you're still hitting a case where your bot cannot reconnect?

**Comment by tonyvanriet** [comment]
Hey @Janiczek 
My bot has stayed up since this fix and I do see some cases where it did a successful reconnect.
Hope you've seen the same.

**Comment by Janiczek** [comment]
I have put this version on our servers and will look out for the bug :) It's shame it can't be more easily reproduced :D

**Comment by Janiczek** [comment]
@tonyvanriet I was "lucky" and found the bot deaf after almost an hour... I am using `"0.1.6-SNAPSHOT"`... Have restarted it since, but if you'll need to conduct some tests inside the REPL, I should be able to run some commands for you.

**Comment by tonyvanriet** [comment]
Sorry to hear it...
Did you happen to catch the log output when it went dead? Did it look similar where it attempted `reconnecting...` but never came back up?
If you can catch the log output, that'll be the best place to start.

**Comment by Janiczek** [comment]
That was the weird thing. No `reconnecting...` in sight. But maybe that was because of some of my REPL prodding inside that live system earlier - I've had one of the earlier instances throw exceptions because of CIDER-instrumented functions and disconnected debugger. This one I won't be doing any weird stuff to and I will capture logs.

**Comment by Janiczek** [comment]
@tonyvanriet It has stayed solid for a few days now. I guess the last error was really because of messing with the REPL and debugger. I think it's okay to close this! Thanks again! :)

**Comment by tonyvanriet** [comment]
Excellent! Glad to hear it.
My bot has been going strong for 2 weeks now, so I'm feeling good about the fix.
